# Generated by Django 4.2.2 on 2023-08-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='myapp/profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
